config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cars

  root 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:weight, :fuel_tank_capacity, :gas_per_kilometer, :tire_radious, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, html: { class: 'form-horizontal' }) do |f| %>
  <% if @car.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:
      </div>
      
      <div class="panel-body">
        <ul>
        <% @car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :weight, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :weight, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :fuel_tank_capacity, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :fuel_tank_capacity, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :gas_per_kilometer, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :gas_per_kilometer, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tire_radious, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :tire_radious, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-9 col-md-offset-3">
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  
  <div class="page-header">
    <h1>Cars <small>Edit car</small></h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-9 col-md-offset-3">
    <%= link_to 'Back', cars_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="page-header">
    <h1>Cars <small>Listing cars</small></h1>
  </div>

  <% unless notice.nil? || notice.empty? %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Weight</th>
        <th>Fuel tank capacity</th>
        <th>Gas per kilometer</th>
        <th>Tire radious</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= car.weight %></td>
          <td><%= car.fuel_tank_capacity %></td>
          <td><%= car.gas_per_kilometer %></td>
          <td><%= car.tire_radious %></td>
          <td><%= car.name %></td>
          <td><%= link_to 'Show', car, class: 'btn btn-small btn-default' %></td>
          <td><%= link_to 'Edit', edit_car_path(car), class: 'btn btn-small btn-info' %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Car', new_car_path, class: 'btn btn-success' %>

</div>

app/views/cars/new.html.erb
<div class="col-md-8 col-md-offset-2">
  
  <div class="page-header">
    <h1>Cars <small>New car</small></h1>
  </div>

  <%= render 'form' %>

  <div class="col-md-9 col-md-offset-3">
    <%= link_to 'Back', cars_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="page-header">
    <h1>Cars <small><%= @car.name %></small></h1>
  </div>
  
  <% unless notice.nil? || notice.empty? %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="list-group">
        <li class="list-group-item">
          <span class="badge"><%= @car.weight %></span>
          Weight:
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @car.fuel_tank_capacity %></span>
          Fuel tank capacity:
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @car.gas_per_kilometer %></span>
          Gas per kilometer:
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @car.tire_radious %></span>
          Tire radious:
        </li>
      </ul>
    </div>
  </div>
  
  <div class="btn-group">
    <%= link_to 'Edit', edit_car_path(@car), class: 'btn btn-info' %>
    <%= link_to 'Back', cars_path, class: 'btn btn-default' %>
  </div>
  
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag('', class: 'form-horizontal', id: 'car_type_form') do %>
      <div class="form-group">
        <%= label_tag :simulation, 'Car type', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= collection_select(:simulation, :car_id, Car.all, :id, :name, { }, { class: 'form-control', id: 'car_select' }) %>
        </div>
      </div>

      <%= submit_tag('Start simulation', class: 'btn btn-success', id: 'start_simulation_button') %>
    <% end %>
  </div>
</div>
<br><br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="col-md-6">
      <div class="row"><div id="speedometer"></div></div>
      <div class="row"><!-- Distance --></div>
    </div>
    <div class="col-md-6">
      <div class="row"><!-- fuel --></div>
      <div class="row">
        <!-- cruise control -->
        <button type="button" class="btn btn-info" data-toggle="button" aria-pressed="false" autocomplete="off">
          Cruise control
        </button>
      </div>
      <div class="row"><!-- angle --></div>
      <div class="row">
      <button type="button" class="btn btn-danger" id="stop_simulation_button">Stop simulation</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <%= link_to 'Cruiser Control', root_path, class: 'navbar-brand' %>
  </div>
  
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cars <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Listing cars', cars_path %></li>
        <li><%= link_to 'New car', new_car_path %></li>
      </ul>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CruiseControl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>

<%= yield %>

</body>
</html>